In [181]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/pasc-data-quest-20-20/doctor_train.csv
/kaggle/input/pasc-data-quest-20-20/doctor_test.csv
/kaggle/input/pasc-data-quest-20-20/sample_submission.csv

In [182]:
X = pd.read_csv("/kaggle/input/pasc-data-quest-20-20/doctor_train.csv")
testF = pd.read_csv("/kaggle/input/pasc-data-quest-20-20/doctor_test.csv")

print(X.shape)
X.head()

(28196, 18)

,ID,age,Profession,Status,edu,Irregular,Money,residence,prev_diagnosed,communication,day,Month,Time,Doctor_visits,last_visit,cured_in,side_effects,Y
0,0,30.0,management,single,tertiary,no,1466.0,no,no,cellular,12,aug,111,4,-1,0,unknown,no
1,1,35.0,student,single,secondary,no,278.0,no,no,unknown,21,sep,84,1,-1,0,unknown,no
2,2,41.0,management,married,tertiary,no,6060.0,yes,no,unknown,15,may,71,2,-1,0,unknown,no
3,3,32.0,blue-collar,married,primary,no,642.0,no,yes,cellular,8,jul,524,1,-1,0,unknown,no
4,4,39.0,admin.,married,secondary,no,2598.0,no,no,cellular,17,nov,123,1,-1,0,unknown,no

In [183]:
testF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID              3000 non-null   int64
 1   age             2919 non-null   float64
 2   Profession      3000 non-null   object
 3   Status          3000 non-null   object
 4   edu             2985 non-null   object
 5   Irregular       3000 non-null   object
 6   Money           2954 non-null   float64
 7   residence       2977 non-null   object
 8   prev_diagnosed  2993 non-null   object
 9   communication   3000 non-null   object
 10  day             3000 non-null   int64
 11  Month           3000 non-null   object
 12  Time            3000 non-null   int64
 13  Doctor_visits   3000 non-null   int64
 14  last_visit      3000 non-null   int64
 15  cured_in        3000 non-null   int64
 16  side_effects    3000 non-null   object
dtypes: float64(2), int64(6), object(9)
memory usage: 398.6+ KB

In [184]:
testF['age'].fillna((testF['age'].mean()), inplace=True)
testF['Money'].fillna((testF['Money'].mean()), inplace=True)

testF["edu"].fillna("None", inplace = True) 
testF["prev_diagnosed"].fillna("None", inplace = True) 
testF["residence"].fillna("None", inplace = True) 

testF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID              3000 non-null   int64
 1   age             3000 non-null   float64
 2   Profession      3000 non-null   object
 3   Status          3000 non-null   object
 4   edu             3000 non-null   object
 5   Irregular       3000 non-null   object
 6   Money           3000 non-null   float64
 7   residence       3000 non-null   object
 8   prev_diagnosed  3000 non-null   object
 9   communication   3000 non-null   object
 10  day             3000 non-null   int64
 11  Month           3000 non-null   object
 12  Time            3000 non-null   int64
 13  Doctor_visits   3000 non-null   int64
 14  last_visit      3000 non-null   int64
 15  cured_in        3000 non-null   int64
 16  side_effects    3000 non-null   object
dtypes: float64(2), int64(6), object(9)
memory usage: 398.6+ KB

In [185]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28196 entries, 0 to 28195
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID              28196 non-null  int64
 1   age             26913 non-null  float64
 2   Profession      28196 non-null  object
 3   Status          28196 non-null  object
 4   edu             27997 non-null  object
 5   Irregular       28196 non-null  object
 6   Money           27449 non-null  float64
 7   residence       28007 non-null  object
 8   prev_diagnosed  28123 non-null  object
 9   communication   28196 non-null  object
 10  day             28196 non-null  int64
 11  Month           28196 non-null  object
 12  Time            28196 non-null  int64
 13  Doctor_visits   28196 non-null  int64
 14  last_visit      28196 non-null  int64
 15  cured_in        28196 non-null  int64
 16  side_effects    28196 non-null  object
 17  Y               28196 non-null  object
dtypes: float64(2), int64(6), object(10)
memory usage: 3.9+ MB

In [186]:
X['age'].fillna((X['age'].mean()), inplace=True)
X['Money'].fillna((X['Money'].mean()), inplace=True)

X["edu"].fillna("None", inplace = True) 
X["prev_diagnosed"].fillna("None", inplace = True) 
X["residence"].fillna("None", inplace = True) 

X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28196 entries, 0 to 28195
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID              28196 non-null  int64
 1   age             28196 non-null  float64
 2   Profession      28196 non-null  object
 3   Status          28196 non-null  object
 4   edu             28196 non-null  object
 5   Irregular       28196 non-null  object
 6   Money           28196 non-null  float64
 7   residence       28196 non-null  object
 8   prev_diagnosed  28196 non-null  object
 9   communication   28196 non-null  object
 10  day             28196 non-null  int64
 11  Month           28196 non-null  object
 12  Time            28196 non-null  int64
 13  Doctor_visits   28196 non-null  int64
 14  last_visit      28196 non-null  int64
 15  cured_in        28196 non-null  int64
 16  side_effects    28196 non-null  object
 17  Y               28196 non-null  object
dtypes: float64(2), int64(6), object(10)
memory usage: 3.9+ MB

In [187]:
print('rows    [X]  ' , X.shape[0])
print('columns [X]  ' , X.shape[1])

print('rows    [testset]  ' , testF.shape[0])
print('columns [testset]  ' , testF.shape[1])

rows    [X]   28196
columns [X]   18
rows    [testset]   3000
columns [testset]   17

In [188]:
del testF["ID"]
del X["ID"]

X.describe()

,age,Money,day,Time,Doctor_visits,last_visit,cured_in
count,28196.000000,28196.000000,28196.000000,28196.000000,28196.000000,28196.000000,28196.000000
mean,40.923346,1379.754381,15.783161,258.037949,2.763229,40.378103,0.594517
std,10.451765,3020.143847,8.349699,258.052440,3.085788,99.974968,2.524904
min,18.000000,-8019.000000,1.000000,0.000000,1.000000,-1.000000,0.000000
25%,33.000000,83.000000,8.000000,103.000000,1.000000,-1.000000,0.000000
50%,40.000000,487.000000,16.000000,179.000000,2.000000,-1.000000,0.000000
75%,48.000000,1400.000000,21.000000,320.000000,3.000000,-1.000000,0.000000
max,95.000000,102127.000000,31.000000,4918.000000,58.000000,850.000000,275.000000

In [189]:
X['age_Range'] = pd.cut(X['age'], bins=[0, 33, 40, 48, 100], labels=[1,2,3,4])
X['Money_Range'] = pd.cut(X['Money'], bins=[-10000, 83, 487, 1400, 202127], labels=[1,2,3,4])
X['day_Range'] = pd.cut(X['day'], bins=[-1, 8, 16, 21, 35], labels=[1,2,3,4])
X['Time_Range'] = pd.cut(X['Time'], bins=[-1, 103, 179, 320, 40000], labels=[1,2,3,4])
X['DoctorVisits_Range'] = pd.cut(X['Doctor_visits'], bins=[0, 1, 2, 3, 58], labels=[1,2,3,4])
#del lastvisit, cured_in probably # check its valuse count below
X['curedIn_Range'] = pd.cut(X['cured_in'], bins=[-1, 0, 1, 3, 275], labels=[1,2,3,4])
X['lastVisit_Range'] = pd.cut(X['last_visit'], bins=[-20, 0, 150, 270, 1000], labels=[1,2,3,4])



testF['age_Range'] = pd.cut(testF['age'], bins=[0, 33, 40, 48, 100], labels=[1,2,3,4])
testF['Money_Range'] = pd.cut(testF['Money'], bins=[-10000, 83, 487, 1400, 202127], labels=[1,2,3,4])
testF['day_Range'] = pd.cut(testF['day'], bins=[-1, 8, 16, 21, 35], labels=[1,2,3,4])
testF['Time_Range'] = pd.cut(testF['Time'], bins=[-1, 103, 179, 320, 40000], labels=[1,2,3,4])
testF['DoctorVisits_Range'] = pd.cut(testF['Doctor_visits'], bins=[0, 1, 2, 3, 58], labels=[1,2,3,4])
#del lastvisit, cured_in probably # check its valuse count below
testF['curedIn_Range'] = pd.cut(testF['cured_in'], bins=[-1, 0, 1, 3, 275], labels=[1,2,3,4])
testF['lastVisit_Range'] = pd.cut(testF['last_visit'], bins=[-20, 0, 150, 270, 1000], labels=[1,2,3,4])


#del the old columns
del X['age']
del X['Money']
del X['day']
del X['Time']
del X['Doctor_visits']
del X['cured_in']
del X['last_visit']

del testF['age']
del testF['Money']
del testF['day']
del testF['Time']
del testF['Doctor_visits']
del testF['cured_in']
del testF['last_visit']

In [190]:
X['age_Range'] = X['age_Range'].astype(int)
X['Money_Range'] = X['Money_Range'].astype(int)
X['day_Range'] = X['day_Range'].astype(int)
X['Time_Range'] = X['Time_Range'].astype(int)
X['DoctorVisits_Range'] = X['DoctorVisits_Range'].astype(int)
X['curedIn_Range'] = X['curedIn_Range'].astype(int)
X['lastVisit_Range'] = X['lastVisit_Range'].astype(int)


testF['age_Range'] = testF['age_Range'].astype(int)
testF['Money_Range'] = testF['Money_Range'].astype(int)
testF['day_Range'] = testF['day_Range'].astype(int)
testF['Time_Range'] = testF['Time_Range'].astype(int)
testF['DoctorVisits_Range'] = testF['DoctorVisits_Range'].astype(int)
testF['curedIn_Range'] = testF['curedIn_Range'].astype(int)
testF['lastVisit_Range'] = testF['lastVisit_Range'].astype(int)

In [191]:
testF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Profession          3000 non-null   object
 1   Status              3000 non-null   object
 2   edu                 3000 non-null   object
 3   Irregular           3000 non-null   object
 4   residence           3000 non-null   object
 5   prev_diagnosed      3000 non-null   object
 6   communication       3000 non-null   object
 7   Month               3000 non-null   object
 8   side_effects        3000 non-null   object
 9   age_Range           3000 non-null   int64
 10  Money_Range         3000 non-null   int64
 11  day_Range           3000 non-null   int64
 12  Time_Range          3000 non-null   int64
 13  DoctorVisits_Range  3000 non-null   int64
 14  curedIn_Range       3000 non-null   int64
 15  lastVisit_Range     3000 non-null   int64
dtypes: int64(7), object(9)
memory usage: 375.1+ KB

In [192]:
X['Month'] = X['Month'].replace(['jan', 'oct','sep', 'mar','dec'], 'Rest')
testF['Month'] = testF['Month'].replace(['jan', 'oct','sep', 'mar','dec'], 'Rest')

X['Profession'] = X['Profession'].replace(['unknown', 'student','housemaid', 'unemployed'], 'Rare1')
X['Profession'] = X['Profession'].replace(['entrepreneur', 'self-employed'], 'Rare2')
testF['Profession'] = testF['Profession'].replace(['unknown', 'student','housemaid', 'unemployed'], 'Rare1')
testF['Profession'] = testF['Profession'].replace(['entrepreneur', 'self-employed'], 'Rare2')


X['Profession'].value_counts()

blue-collar    6024
management     5904
technician     4722
admin.         3243
services       2589
Rare1          2332
Rare2          1954
retired        1428
Name: Profession, dtype: int64

In [193]:
X['Y'] = X['Y'].replace(['yes'], 1)
X['Y'] = X['Y'].replace(['no'], 0)

X["Y"].value_counts()

0    24887
1     3309
Name: Y, dtype: int64

In [194]:
#make one hot vectors
X_new = pd.get_dummies(X, columns = ["Profession","Status","edu","Irregular","residence","prev_diagnosed","communication","Month","side_effects"],
                             prefix=[ "Prof","Status","edu","Irr","resi","prevD","comm","Month","SideE"])

testF_new = pd.get_dummies(testF, columns = ["Profession","Status","edu","Irregular","residence","prev_diagnosed","communication","Month","side_effects"],
                             prefix=[ "Prof","Status","edu","Irr","resi","prevD","comm","Month","SideE"])


X_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28196 entries, 0 to 28195
Data columns (total 47 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Y                   28196 non-null  int64
 1   age_Range           28196 non-null  int64
 2   Money_Range         28196 non-null  int64
 3   day_Range           28196 non-null  int64
 4   Time_Range          28196 non-null  int64
 5   DoctorVisits_Range  28196 non-null  int64
 6   curedIn_Range       28196 non-null  int64
 7   lastVisit_Range     28196 non-null  int64
 8   Prof_Rare1          28196 non-null  uint8
 9   Prof_Rare2          28196 non-null  uint8
 10  Prof_admin.         28196 non-null  uint8
 11  Prof_blue-collar    28196 non-null  uint8
 12  Prof_management     28196 non-null  uint8
 13  Prof_retired        28196 non-null  uint8
 14  Prof_services       28196 non-null  uint8
 15  Prof_technician     28196 non-null  uint8
 16  Status_divorced     28196 non-null  uint8
 17  Status_married      28196 non-null  uint8
 18  Status_single       28196 non-null  uint8
 19  edu_None            28196 non-null  uint8
 20  edu_primary         28196 non-null  uint8
 21  edu_secondary       28196 non-null  uint8
 22  edu_tertiary        28196 non-null  uint8
 23  edu_unknown         28196 non-null  uint8
 24  Irr_no              28196 non-null  uint8
 25  Irr_yes             28196 non-null  uint8
 26  resi_None           28196 non-null  uint8
 27  resi_no             28196 non-null  uint8
 28  resi_yes            28196 non-null  uint8
 29  prevD_None          28196 non-null  uint8
 30  prevD_no            28196 non-null  uint8
 31  prevD_yes           28196 non-null  uint8
 32  comm_cellular       28196 non-null  uint8
 33  comm_telephone      28196 non-null  uint8
 34  comm_unknown        28196 non-null  uint8
 35  Month_Rest          28196 non-null  uint8
 36  Month_apr           28196 non-null  uint8
 37  Month_aug           28196 non-null  uint8
 38  Month_feb           28196 non-null  uint8
 39  Month_jul           28196 non-null  uint8
 40  Month_jun           28196 non-null  uint8
 41  Month_may           28196 non-null  uint8
 42  Month_nov           28196 non-null  uint8
 43  SideE_failure       28196 non-null  uint8
 44  SideE_other         28196 non-null  uint8
 45  SideE_success       28196 non-null  uint8
 46  SideE_unknown       28196 non-null  uint8
dtypes: int64(8), uint8(39)
memory usage: 2.8 MB

In [195]:
X_new["Y"].value_counts()

0    24887
1     3309
Name: Y, dtype: int64

In [196]:
from sklearn.utils import resample
df_majority = X_new[X_new.Y==0]
df_minority = X_new[X_new.Y==1]

df_minority_upsampled = resample(df_minority, 
                                 replace=True,     # sample with replacement
                                 n_samples=14000,    # to match majority class
                                 random_state=123)

df_upsampled = pd.concat([df_majority, df_minority_upsampled])
#df_upsampled.Y.value_counts()

df_majority_downsampled = resample(df_majority, 
                                 replace=False,    # sample without replacement
                                 n_samples=15000,     # to match minority class
                                 random_state=123)

df_downsampled = pd.concat([df_majority_downsampled, df_minority_upsampled])
df_downsampled.Y.value_counts()

0    15000
1    14000
Name: Y, dtype: int64

In [197]:
X_new = df_downsampled
Y_new = X_new["Y"]
del X_new["Y"]

X_resampled = X_new
y_resampled = Y_new

In [142]:
Y_new = X_new["Y"]
del X_new["Y"]

from imblearn.over_sampling import SMOTE, ADASYN
from sklearn.svm import LinearSVC
from collections import Counter

X_resampled, y_resampled = SMOTE().fit_resample(X_new, Y_new)
print(sorted(Counter(y_resampled).items()))

clf_smote = LinearSVC().fit(X_resampled, y_resampled)

[(0, 24887), (1, 24887)]

/opt/conda/lib/python3.7/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

In [198]:
y_resampled.value_counts()

0    15000
1    14000
Name: Y, dtype: int64

In [199]:
y_resampled.shape

(29000,)

In [200]:
X_resampled.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 29000 entries, 18658 to 11498
Data columns (total 46 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   age_Range           29000 non-null  int64
 1   Money_Range         29000 non-null  int64
 2   day_Range           29000 non-null  int64
 3   Time_Range          29000 non-null  int64
 4   DoctorVisits_Range  29000 non-null  int64
 5   curedIn_Range       29000 non-null  int64
 6   lastVisit_Range     29000 non-null  int64
 7   Prof_Rare1          29000 non-null  uint8
 8   Prof_Rare2          29000 non-null  uint8
 9   Prof_admin.         29000 non-null  uint8
 10  Prof_blue-collar    29000 non-null  uint8
 11  Prof_management     29000 non-null  uint8
 12  Prof_retired        29000 non-null  uint8
 13  Prof_services       29000 non-null  uint8
 14  Prof_technician     29000 non-null  uint8
 15  Status_divorced     29000 non-null  uint8
 16  Status_married      29000 non-null  uint8
 17  Status_single       29000 non-null  uint8
 18  edu_None            29000 non-null  uint8
 19  edu_primary         29000 non-null  uint8
 20  edu_secondary       29000 non-null  uint8
 21  edu_tertiary        29000 non-null  uint8
 22  edu_unknown         29000 non-null  uint8
 23  Irr_no              29000 non-null  uint8
 24  Irr_yes             29000 non-null  uint8
 25  resi_None           29000 non-null  uint8
 26  resi_no             29000 non-null  uint8
 27  resi_yes            29000 non-null  uint8
 28  prevD_None          29000 non-null  uint8
 29  prevD_no            29000 non-null  uint8
 30  prevD_yes           29000 non-null  uint8
 31  comm_cellular       29000 non-null  uint8
 32  comm_telephone      29000 non-null  uint8
 33  comm_unknown        29000 non-null  uint8
 34  Month_Rest          29000 non-null  uint8
 35  Month_apr           29000 non-null  uint8
 36  Month_aug           29000 non-null  uint8
 37  Month_feb           29000 non-null  uint8
 38  Month_jul           29000 non-null  uint8
 39  Month_jun           29000 non-null  uint8
 40  Month_may           29000 non-null  uint8
 41  Month_nov           29000 non-null  uint8
 42  SideE_failure       29000 non-null  uint8
 43  SideE_other         29000 non-null  uint8
 44  SideE_success       29000 non-null  uint8
 45  SideE_unknown       29000 non-null  uint8
dtypes: int64(7), uint8(39)
memory usage: 2.8 MB

X_resampled['age_Range'].fillna(2, inplace=True)
X_resampled['Money_Range'].fillna(2, inplace=True)

X_resampled['day_Range'].fillna(2, inplace=True)

X_resampled['Time_Range'].fillna(2, inplace=True)
X_resampled['DoctorVisits_Range'].fillna(2, inplace=True)
X_resampled['curedIn_Range'].fillna(2, inplace=True)
X_resampled['lastVisit_Range'].fillna(2, inplace=True)
#testF["residence"].fillna("None", inplace = True)

In [201]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.33, random_state=2)

X_train

,age_Range,Money_Range,day_Range,Time_Range,DoctorVisits_Range,curedIn_Range,lastVisit_Range,Prof_Rare1,Prof_Rare2,Prof_admin.,...,Month_aug,Month_feb,Month_jul,Month_jun,Month_may,Month_nov,SideE_failure,SideE_other,SideE_success,SideE_unknown
6691,3,4,4,4,2,2,3,0,0,0,...,0,0,0,1,0,0,0,0,1,0
25821,1,2,2,2,1,1,1,1,0,0,...,1,0,0,0,0,0,0,0,0,1
6699,3,1,3,1,2,3,3,0,0,0,...,0,0,0,0,0,1,1,0,0,0
9249,3,1,2,4,2,1,1,0,0,0,...,0,0,1,0,0,0,0,0,0,1
15638,4,2,2,4,2,3,4,0,0,0,...,0,0,0,0,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26515,1,4,4,4,1,3,4,0,0,0,...,0,0,0,0,0,0,1,0,0,0
23219,1,3,1,2,2,1,1,0,0,0,...,1,0,0,0,0,0,0,0,0,1
12671,3,1,2,2,1,1,1,0,0,0,...,0,0,0,0,1,0,0,0,0,1
22031,2,4,3,3,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
21355,4,1,4,4,3,3,2,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [202]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 19430 entries, 6691 to 21355
Data columns (total 46 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   age_Range           19430 non-null  int64
 1   Money_Range         19430 non-null  int64
 2   day_Range           19430 non-null  int64
 3   Time_Range          19430 non-null  int64
 4   DoctorVisits_Range  19430 non-null  int64
 5   curedIn_Range       19430 non-null  int64
 6   lastVisit_Range     19430 non-null  int64
 7   Prof_Rare1          19430 non-null  uint8
 8   Prof_Rare2          19430 non-null  uint8
 9   Prof_admin.         19430 non-null  uint8
 10  Prof_blue-collar    19430 non-null  uint8
 11  Prof_management     19430 non-null  uint8
 12  Prof_retired        19430 non-null  uint8
 13  Prof_services       19430 non-null  uint8
 14  Prof_technician     19430 non-null  uint8
 15  Status_divorced     19430 non-null  uint8
 16  Status_married      19430 non-null  uint8
 17  Status_single       19430 non-null  uint8
 18  edu_None            19430 non-null  uint8
 19  edu_primary         19430 non-null  uint8
 20  edu_secondary       19430 non-null  uint8
 21  edu_tertiary        19430 non-null  uint8
 22  edu_unknown         19430 non-null  uint8
 23  Irr_no              19430 non-null  uint8
 24  Irr_yes             19430 non-null  uint8
 25  resi_None           19430 non-null  uint8
 26  resi_no             19430 non-null  uint8
 27  resi_yes            19430 non-null  uint8
 28  prevD_None          19430 non-null  uint8
 29  prevD_no            19430 non-null  uint8
 30  prevD_yes           19430 non-null  uint8
 31  comm_cellular       19430 non-null  uint8
 32  comm_telephone      19430 non-null  uint8
 33  comm_unknown        19430 non-null  uint8
 34  Month_Rest          19430 non-null  uint8
 35  Month_apr           19430 non-null  uint8
 36  Month_aug           19430 non-null  uint8
 37  Month_feb           19430 non-null  uint8
 38  Month_jul           19430 non-null  uint8
 39  Month_jun           19430 non-null  uint8
 40  Month_may           19430 non-null  uint8
 41  Month_nov           19430 non-null  uint8
 42  SideE_failure       19430 non-null  uint8
 43  SideE_other         19430 non-null  uint8
 44  SideE_success       19430 non-null  uint8
 45  SideE_unknown       19430 non-null  uint8
dtypes: int64(7), uint8(39)
memory usage: 1.9 MB

In [203]:
y_train.value_counts()

0    10033
1     9397
Name: Y, dtype: int64

In [204]:
from sklearn.model_selection import GridSearchCV
param_grid = [{
              'max_depth': [3, 5, 7, 8],
              'n_estimators' : [100,150,200,250],
              'max_features': ["auto", "sqrt", "log2"]
            }]
reg = XGBClassifier(random_state=40)
# Instantiate the grid search model
grid_search = GridSearchCV(estimator = reg, param_grid = param_grid, cv = 5, n_jobs = -1 , scoring='r2' , verbose=2)
grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 48 candidates, totalling 240 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.

KeyboardInterrupt:

In [205]:
from xgboost import XGBClassifier
model = XGBClassifier(max_depth=4, n_estimators=700)

model.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster=None, colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints=None,
              learning_rate=0.300000012, max_delta_step=0, max_depth=4,
              min_child_weight=1, missing=nan, monotone_constraints=None,
              n_estimators=700, n_jobs=0, num_parallel_tree=1,
              objective='binary:logistic', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=1, subsample=1, tree_method=None,
              validate_parameters=False, verbosity=None)

In [206]:
y_pred = model.predict(X_test)
predictions = [round(value) for value in y_pred]
print(np.shape(predictions))

(9570,)

In [207]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, predictions)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

Accuracy: 88.70%

In [208]:
predictions

[0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 ...]

In [209]:
#answer
y_pred = model.predict(testF_new)
predictions = [round(value) for value in y_pred]
print(np.shape(predictions))

sample_submission = pd.read_csv("/kaggle/input/pasc-data-quest-20-20/sample_submission.csv")
sample_submission["Y"] = predictions

sample_submission["Y"] = sample_submission["Y"].replace([1], 'yes')
sample_submission["Y"] = sample_submission["Y"].replace([0], 'no')


sample_submission.to_csv('submissions.csv', header=True, index=False)
sample_submission.head()

(3000,)

   ID    Y
0   0   no
1   1  yes
2   2   no
3   3  yes
4   4   no

In [210]:
sample_submission["Y"].value_counts()

no     1648
yes    1352
Name: Y, dtype: int64